PRODUCTS = {
    # Dry Fruits
    "almond": "dryfruits",
    "almonds": "dryfruits",
    "badam": "dryfruits",
    "badaam": "dryfruits",
    "dates": "dryfruits",
    "khajoor": "dryfruits",
    "khajur": "dryfruits",
    "pistachio": "dryfruits",
    "pista": "dryfruits",
    "pistachios": "dryfruits",
    "walnut": "dryfruits",
    "walnuts": "dryfruits",
    "akhrot": "dryfruits",
    "peanut": "dryfruits",
    "peanuts": "dryfruits",
    "mungfali": "dryfruits",
    "moongphali": "dryfruits",
    "pine nut": "dryfruits",
    "pine nuts": "dryfruits",
    "chilgoza": "dryfruits",
    "pecan": "dryfruits",
    "pecans": "dryfruits",
    "raisins": "dryfruits",
    "kishmish": "dryfruits",
    "pumpkin seeds": "dryfruits",
    "pumpkin seed": "dryfruits",
    "sunflower seeds": "dryfruits",
    "sunflower seed": "dryfruits",
    "watermelon seeds": "dryfruits",
    "watermelon seed": "dryfruits",
    "kaju": "dryfruits",
    "kajuu": "dryfruits",
    "kaju nuts": "dryfruits",
    "cashew": "dryfruits",
    "cashews": "dryfruits",
    "cashewnut": "dryfruits",
    "cashew nut": "dryfruits",
    "cashew nuts": "dryfruits",

    # Spices
    "cumin": "spices",
    "jeera": "spices",
    "zeera": "spices",
    "coriander": "spices",
    "dhaniya": "spices",
    "dhania": "spices",
    "black pepper": "spices",
    "blackpepper": "spices",
    "kali mirch": "spices",
    "white pepper": "spices",
    "whitepepper": "spices",
    "cloves": "spices",
    "laung": "spices",
    "long": "spices",
    "ginger": "spices",
    "adrak": "spices",
    "turmeric": "spices",
    "haldi": "spices",
    "cinnamon": "spices",
    "dalchini": "spices",
    "bay leaf": "spices",
    "bayleaf": "spices",
    "tej patta": "spices",
    "fenugreek": "spices",
    "methi": "spices",
    "fennel": "spices",
    "saunf": "spices",
    "ajwain": "spices",
    "carom": "spices",
    "sesame": "spices",
    "til": "spices",
    "red chili": "spices",
    "red chili powder": "spices",
    "red chilli": "spices",
    "lal mirch": "spices",
    "anise": "spices",
    "aniseed": "spices",

    # Fruits
    "apple": "fruits",
    "apples": "fruits",
    "seb": "fruits",
    "coconut": "fruits",
    "coconuts": "fruits",
    "nariyal": "fruits",

    # Grains
    "barley": "grains",
    "jau": "grains",
    "rice": "grains",
    "chawal": "grains",
    "brown rice": "grains",
    "basmati": "grains",
    "basmati rice": "grains",
    "wheat": "grains",
    "gehu": "grains",
    "atta": "grains",
    "whole wheat": "grains",
    "oats": "grains",
    "jai": "grains",
    "millet": "grains",
    "bajra": "grains",
    "jowar": "grains",
    "ragi": "grains",
    "quinoa": "grains",

    # Vegetables
    "corn": "vegetables",
    "makkai": "vegetables",
    "maize": "vegetables",
    "onion": "vegetables",
    "onions": "vegetables",
    "pyaaz": "vegetables",
    "kanda": "vegetables",
    "potato": "vegetables",
    "potatoes": "vegetables",
    "aaloo": "vegetables",
    "aloo": "vegetables",
    "tomato": "vegetables",
    "tomatoes": "vegetables",
    "tamatar": "vegetables",
    "garlic": "vegetables",
    "lehsun": "vegetables",
    "lassan": "vegetables",
    "green chili": "vegetables",
    "green chillies": "vegetables",
    "hari mirch": "vegetables",
    "capsicum": "vegetables",
    "shimla mirch": "vegetables",
    "carrot": "vegetables",
    "carrots": "vegetables",
    "gajar": "vegetables",
    "cauliflower": "vegetables",
    "gobi": "vegetables",
    "cabbage": "vegetables",
    "patta gobi": "vegetables",
    "peas": "vegetables",
    "matar": "vegetables",
    "spinach": "vegetables",
    "palak": "vegetables",
    "brinjal": "vegetables",
    "baingan": "vegetables",
    "eggplant": "vegetables",
    "bitter gourd": "vegetables",
    "karela": "vegetables",
    "bottle gourd": "vegetables",
    "lauki": "vegetables",
    "pumpkin": "vegetables",
    "kaddu": "vegetables",
    "ladyfinger": "vegetables",
    "bhindi": "vegetables",
    "okra": "vegetables",
    "beetroot": "vegetables",
    "chukandar": "vegetables",
    "radish": "vegetables",
    "mooli": "vegetables",
    "cucumber": "vegetables",
    "kheera": "vegetables",
    "lemon": "vegetables",
    "nimbu": "vegetables",

    # Fruits
    "apple": "fruits",
    "apples": "fruits",
    "seb": "fruits",
    "coconut": "fruits",
    "coconuts": "fruits",
    "nariyal": "fruits",
    "mango": "fruits",
    "mangoes": "fruits",
    "aam": "fruits",
    "banana": "fruits",
    "bananas": "fruits",
    "kela": "fruits",
    "orange": "fruits",
    "oranges": "fruits",
    "santara": "fruits",
    "mosambi": "fruits",
    "sweet lime": "fruits",
    "grape": "fruits",
    "grapes": "fruits",
    "angoor": "fruits",
    "pomegranate": "fruits",
    "anar": "fruits",
    "papaya": "fruits",
    "papita": "fruits",
    "pineapple": "fruits",
    "ananas": "fruits",
    "watermelon": "fruits",
    "tarbooz": "fruits",
    "muskmelon": "fruits",
    "kharbooja": "fruits",
    "guava": "fruits",
    "amrood": "fruits",
    "jackfruit": "fruits",
    "kathal": "fruits",
    "sapota": "fruits",
    "chikoo": "fruits",
    "custard apple": "fruits",
    "sitaphal": "fruits",

    # Category-level keys (not specific products)
    "dry fruit": "dryfruits",
    "dry fruits": "dryfruits",
    "dryfruits": "dryfruits",
    "nuts": "dryfruits",
    "spices": "spices",
    "fruits": "fruits",
    "vegetables": "vegetables",
    "grains": "grains"
}
